[build-system]
requires = ["setuptools>=77.0.3", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "galaxy-udload"
dynamic = ["version"]
description = "File utility to upload or download file from or to UseGalaxy"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [
    { name = "Charles Coulombe" },
    { name = "Carol Gauthier" },
]

dependencies = [
    "bioblend",
    "python-dotenv",
    "rich",
]

[project.optional-dependencies]
docs = [
    "mkdocs-material>=9.7.1",
    "click==8.2.1" # bug with mkdocs livereload with higher version
]

[project.scripts]
galaxy = "galaxy_udload.main:main"

[tool.setuptools]
packages = ["galaxy_udload"]

[tool.setuptools_scm]
write_to = "galaxy_udload/_version.py"
